name: 'Execução Manual - Atividade Avaliativa'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Realize Checkout
        uses: actions/checkout@v4

      - name: Install Node v18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Inspect Lint
        run: npm run check_format

      - name: Execute Tests
        run: npm run test
